apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $APP_NAME-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "${STATIC_IP_NAME}"
spec:
  defaultBackend:
    service:
      name: $APP_NAME-service
      port:
        number: 80